/**
 * Generated Timeline Event Metadata for Eligian Code Completion
 *
 * DO NOT EDIT THIS FILE MANUALLY - Generated by src/completion/generate-metadata.ts
 *
 * This file contains metadata imported from the Eligius npm package.
 * Source: import { TimelineEventNames } from 'eligius' (version from packages/language/package.json)
 */

export interface TimelineEventMetadata {
  name: string;
  description: string;
  category?: string;
}

/**
 * All Eligius timeline events (alphabetically sorted)
 * Total events: 33
 */
export const TIMELINE_EVENTS: TimelineEventMetadata[] = [
  {
    "name": "before-request-timeline-uri",
    "description": "Timeline event: BEFORE_REQUEST_TIMELINE_URI",
    "category": "general"
  },
  {
    "name": "language-change",
    "description": "Timeline event: LANGUAGE_CHANGE",
    "category": "general"
  },
  {
    "name": "request-action",
    "description": "Timeline event: REQUEST_ACTION",
    "category": "factory"
  },
  {
    "name": "request-current-language",
    "description": "Timeline event: REQUEST_CURRENT_LANGUAGE",
    "category": "factory"
  },
  {
    "name": "request-current-timeline-position",
    "description": "Timeline event: REQUEST_CURRENT_TIMELINE_POSITION",
    "category": "factory"
  },
  {
    "name": "request-engine-root",
    "description": "Timeline event: REQUEST_ENGINE_ROOT",
    "category": "factory"
  },
  {
    "name": "request-function",
    "description": "Timeline event: REQUEST_FUNCTION",
    "category": "factory"
  },
  {
    "name": "request-instance",
    "description": "Timeline event: REQUEST_INSTANCE",
    "category": "factory"
  },
  {
    "name": "request-label-collection",
    "description": "Timeline event: REQUEST_LABEL_COLLECTION",
    "category": "factory"
  },
  {
    "name": "request-label-collections",
    "description": "Timeline event: REQUEST_LABEL_COLLECTIONS",
    "category": "factory"
  },
  {
    "name": "request-timeline-cleanup",
    "description": "Timeline event: REQUEST_TIMELINE_CLEANUP",
    "category": "factory"
  },
  {
    "name": "request-timeline-uri",
    "description": "Timeline event: REQUEST_TIMELINE_URI",
    "category": "factory"
  },
  {
    "name": "timeline-complete",
    "description": "Timeline event: COMPLETE",
    "category": "announcements"
  },
  {
    "name": "timeline-container-request",
    "description": "Timeline event: CONTAINER_REQUEST",
    "category": "requests"
  },
  {
    "name": "timeline-current-timeline-change",
    "description": "Timeline event: CURRENT_TIMELINE_CHANGE",
    "category": "announcements"
  },
  {
    "name": "timeline-duration",
    "description": "Timeline event: DURATION",
    "category": "announcements"
  },
  {
    "name": "timeline-duration-request",
    "description": "Timeline event: DURATION_REQUEST",
    "category": "requests"
  },
  {
    "name": "timeline-firstframe",
    "description": "Timeline event: FIRST_FRAME",
    "category": "announcements"
  },
  {
    "name": "timeline-pause",
    "description": "Timeline event: PAUSE",
    "category": "announcements"
  },
  {
    "name": "timeline-pause-request",
    "description": "Timeline event: PAUSE_REQUEST",
    "category": "requests"
  },
  {
    "name": "timeline-play",
    "description": "Timeline event: PLAY",
    "category": "announcements"
  },
  {
    "name": "timeline-play-request",
    "description": "Timeline event: PLAY_REQUEST",
    "category": "requests"
  },
  {
    "name": "timeline-play-toggle-request",
    "description": "Timeline event: PLAY_TOGGLE_REQUEST",
    "category": "requests"
  },
  {
    "name": "timeline-request-current-timeline",
    "description": "Timeline event: REQUEST_CURRENT_TIMELINE",
    "category": "factory"
  },
  {
    "name": "timeline-resize",
    "description": "Timeline event: RESIZE",
    "category": "announcements"
  },
  {
    "name": "timeline-resize-request",
    "description": "Timeline event: RESIZE_REQUEST",
    "category": "requests"
  },
  {
    "name": "timeline-restart",
    "description": "Timeline event: RESTART",
    "category": "announcements"
  },
  {
    "name": "timeline-seek",
    "description": "Timeline event: SEEK",
    "category": "announcements"
  },
  {
    "name": "timeline-seek-request",
    "description": "Timeline event: SEEK_REQUEST",
    "category": "requests"
  },
  {
    "name": "timeline-seeked",
    "description": "Timeline event: SEEKED",
    "category": "announcements"
  },
  {
    "name": "timeline-stop",
    "description": "Timeline event: STOP",
    "category": "announcements"
  },
  {
    "name": "timeline-stop-request",
    "description": "Timeline event: STOP_REQUEST",
    "category": "requests"
  },
  {
    "name": "timeline-time",
    "description": "Timeline event: TIME",
    "category": "announcements"
  }
];
