/**
 * Generated Operation Registry
 *
 * This file is auto-generated by generate-registry.ts
 * DO NOT EDIT MANUALLY - changes will be overwritten
 *
 * Generated: 2025-11-02T17:37:54.788Z
 * Total operations: 79
 */

import type { OperationRegistry } from './types.js';

export const OPERATION_REGISTRY: OperationRegistry = {
  "addClass": {
    "systemName": "addClass",
    "description": "This operation adds the specified class name to the specified selected element.",
    "parameters": [
      {
        "name": "className",
        "type": [
          "ParameterType:className"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "DOM"
  },
  "addControllerToElement": {
    "systemName": "addControllerToElement",
    "description": "This operation adds the specified controller instance to the given selected element.",
    "parameters": [],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      },
      {
        "name": "controllerInstance",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "Controller"
  },
  "addGlobalsToOperation": {
    "systemName": "addGlobalsToOperation",
    "description": "This operation adds the specified global property names to the current operation data.\nIt finally removes the `globalProperties` property from the current operation data.",
    "parameters": [
      {
        "name": "globalProperties",
        "type": [
          "ParameterType:array"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Data"
  },
  "animate": {
    "systemName": "animate",
    "description": "This operation animates the specified selected element with the given [jQuery animation](https://api.jquery.com/animate/) properties, duration and easing.\nIt resolves after the animation completes.",
    "parameters": [
      {
        "name": "animationProperties",
        "type": [
          "ParameterType:object"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "animationDuration",
        "type": [
          "ParameterType:number"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "animationEasing",
        "type": [
          "ParameterType:boolean"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "Animation"
  },
  "animateWithClass": {
    "systemName": "animateWithClass",
    "description": "This operation adds the specified class name to the specified selected element and assumes that this\nclass triggers and animation on the selected element. It then waits for this animation to complete\nbefore it resolves.",
    "parameters": [
      {
        "name": "className",
        "type": [
          "ParameterType:className"
        ],
        "required": true
      },
      {
        "name": "removeClass",
        "type": [
          "ParameterType:boolean"
        ],
        "required": false
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "Animation"
  },
  "announceToScreenReader": {
    "systemName": "announceToScreenReader",
    "description": "Announces a message to screen readers using an ARIA live region.",
    "parameters": [
      {
        "name": "message",
        "type": [
          "ParameterType:string"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "priority",
        "type": [
          {
            "value": "polite"
          },
          {
            "value": "assertive"
          }
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Accessibility"
  },
  "breakForEach": {
    "systemName": "breakForEach",
    "description": "This operation should only be used within a loop, so between a {@link forEach} and {@link endForEach}\noperation. This operation immediately moves to the loop end index, effectively stopping the loop.",
    "parameters": [],
    "dependencies": [],
    "outputs": [],
    "category": "Control Flow"
  },
  "broadcastEvent": {
    "systemName": "broadcastEvent",
    "description": "This operation broadcasts the given event through the eventbus, along with the\nevent arguments and optional event topic.",
    "parameters": [
      {
        "name": "eventArgs",
        "type": [
          "ParameterType:array"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "eventName",
        "type": [
          "ParameterType:eventName"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "eventTopic",
        "type": [
          "ParameterType:eventTopic"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Utility"
  },
  "calc": {
    "systemName": "calc",
    "description": "This operation calculates the given left and right hand operands using the specified operator.",
    "parameters": [
      {
        "name": "left",
        "type": [
          "ParameterType:number"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "right",
        "type": [
          "ParameterType:number"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "operator",
        "type": [
          {
            "value": "+"
          },
          {
            "value": "-"
          },
          {
            "value": "*"
          },
          {
            "value": "/"
          },
          {
            "value": "%"
          },
          {
            "value": "**"
          }
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "calculationResult",
        "type": [
          "ParameterType:number"
        ]
      }
    ],
    "category": "Utility"
  },
  "clearElement": {
    "systemName": "clearElement",
    "description": "This operation removes all of the children from the given selected element.",
    "parameters": [],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "DOM"
  },
  "clearOperationData": {
    "systemName": "clearOperationData",
    "description": "This operation removes all of the properties on the current operation date.\nOr, if the `properties` property is set only removes the properties defined by that list.",
    "parameters": [
      {
        "name": "properties",
        "type": [
          "ParameterType:array"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Data"
  },
  "clearStorage": {
    "systemName": "clearStorage",
    "description": "Clears data from browser storage (localStorage or sessionStorage).\n\nIf `key` is provided, removes only that key. If `key` is omitted, clears all storage.",
    "parameters": [
      {
        "name": "storageType",
        "type": [
          {
            "value": "local"
          },
          {
            "value": "session"
          }
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "key",
        "type": [
          "ParameterType:string"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Data"
  },
  "compareDate": {
    "systemName": "compareDate",
    "description": "Compares two dates.\ncomparison: -1 (before), 0 (equal), 1 (after)",
    "parameters": [
      {
        "name": "date1",
        "type": [
          {
            "value": "string"
          },
          {
            "value": "number"
          },
          {
            "value": "Date"
          }
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "date2",
        "type": [
          {
            "value": "string"
          },
          {
            "value": "number"
          },
          {
            "value": "Date"
          }
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "comparison",
        "type": [
          "ParameterType:number"
        ]
      },
      {
        "name": "isEqual",
        "type": [
          "ParameterType:boolean"
        ]
      },
      {
        "name": "isBefore",
        "type": [
          "ParameterType:boolean"
        ]
      },
      {
        "name": "isAfter",
        "type": [
          "ParameterType:boolean"
        ]
      }
    ],
    "category": "Date"
  },
  "concatenateStrings": {
    "systemName": "concatenateStrings",
    "description": "Concatenates multiple strings with an optional separator.",
    "parameters": [
      {
        "name": "strings",
        "type": [
          "ParameterType:array"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "separator",
        "type": [
          "ParameterType:string"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "result",
        "type": [
          "ParameterType:string"
        ]
      }
    ],
    "category": "String"
  },
  "continueForEach": {
    "systemName": "continueForEach",
    "description": "This operation should only be used within a loop, so between a {@link forEach} and {@link endForEach}\noperation. This operation immediately moves to the next loop index, effectively canceling the rest\nof the operations in the current iteration.",
    "parameters": [],
    "dependencies": [],
    "outputs": [],
    "category": "Control Flow"
  },
  "createElement": {
    "systemName": "createElement",
    "description": "This operation creates the DOM element described by the given elementName and attributes and assigns\nthe instance to the `template` property on the current operation data.",
    "parameters": [
      {
        "name": "elementName",
        "type": [
          "ParameterType:htmlElementName"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "text",
        "type": [
          "ParameterType:string"
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "attributes",
        "type": [
          "ParameterType:object"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "template",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "DOM"
  },
  "customFunction": {
    "systemName": "customFunction",
    "description": "This operation retrieves a custom function defined by the given system name\nand invokes it with the current operation data and eventbus.",
    "parameters": [
      {
        "name": "systemName",
        "type": [
          "ParameterType:systemName"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Utility"
  },
  "endAction": {
    "systemName": "endAction",
    "description": "This operation invokes the {@link EndableAction}.end method on the specified action instance.\n\nThe action operation data is first merged with the current operation data before it is\npassed on to the action. After the action has completed the action operation data properties\nare removed from the current operation data.",
    "parameters": [
      {
        "name": "actionOperationData",
        "type": [
          "ParameterType:object"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "actionInstance",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "Action"
  },
  "endForEach": {
    "systemName": "endForEach",
    "description": "This operation checks if the current loop should end or start the next iteration.",
    "parameters": [],
    "dependencies": [],
    "outputs": [],
    "category": "Control Flow"
  },
  "endWhen": {
    "systemName": "endWhen",
    "description": "This operation cleans up after the {@link when}/{@link otherwise}/{@link endWhen} control flow ends.",
    "parameters": [],
    "dependencies": [],
    "outputs": [],
    "category": "Control Flow"
  },
  "extendController": {
    "systemName": "extendController",
    "description": "Extends the current controller with given extension.",
    "parameters": [
      {
        "name": "controllerExtension",
        "type": [
          "ParameterType:object"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "controllerInstance",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "Controller"
  },
  "filterArray": {
    "systemName": "filterArray",
    "description": "Filters an array based on property equality or custom predicate function.\n\nOperates on arrayData passed from previous operations.\nSupports two filtering modes:\n1. Property equality: `filterProperty` and `filterValue` to filter by property match\n2. Custom predicate: `filterPredicate` function for complex filtering logic",
    "parameters": [
      {
        "name": "filterProperty",
        "type": [
          "ParameterType:string"
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "filterValue",
        "type": [
          "ParameterType:object"
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "filterPredicate",
        "type": [
          "ParameterType:function"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "arrayData",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "filteredArray",
        "type": [
          "ParameterType:array"
        ]
      }
    ],
    "category": "Array"
  },
  "findInArray": {
    "systemName": "findInArray",
    "description": "Finds the first element in an array matching criteria.\n\nOperates on arrayData passed from previous operations.\nSupports two search modes:\n1. Property equality: `findProperty` and `findValue` to find by property match\n2. Custom predicate: `findPredicate` function for complex search logic\n\nReturns `undefined` for `foundItem` and `-1` for `foundIndex` if no match found.",
    "parameters": [
      {
        "name": "findProperty",
        "type": [
          "ParameterType:string"
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "findValue",
        "type": [
          "ParameterType:object"
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "findPredicate",
        "type": [
          "ParameterType:function"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "arrayData",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "foundItem",
        "type": [
          "ParameterType:object"
        ]
      },
      {
        "name": "foundIndex",
        "type": [
          "ParameterType:number"
        ]
      }
    ],
    "category": "Array"
  },
  "forEach": {
    "systemName": "forEach",
    "description": "This operation iterates over the given collection.\n\nEach iteration the current item from the specified collection is\nassigned to the {@link IOperationScope.currentItem |currentItem} property on the {@link IOperationScope |operation scope}.\n\nAt the start of the loop, the associated {@link endForEach} operation is determined and when\nthe last iteration is completed the flow control is set to the index of that operation.\n\nThe {@link continueForEach |continue} and {@link breakForEach |break} operations can be used to control the\nloop iterations.",
    "parameters": [
      {
        "name": "collection",
        "type": [
          "ParameterType:array",
          "ParameterType:string"
        ],
        "required": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Control Flow"
  },
  "formatDate": {
    "systemName": "formatDate",
    "description": "Formats a date using Intl.DateTimeFormat or simple patterns.",
    "parameters": [
      {
        "name": "format",
        "type": [
          "ParameterType:string"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "date",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "formattedDate",
        "type": [
          "ParameterType:string"
        ]
      }
    ],
    "category": "Date"
  },
  "formatText": {
    "systemName": "formatText",
    "description": "Transforms text using format operations: uppercase, lowercase, capitalize, titlecase, or trim.\n\nOperates on textContent passed from previous operations (e.g., getTextContent).\n\nTransformations:\n- `uppercase`: Convert all characters to uppercase\n- `lowercase`: Convert all characters to lowercase\n- `capitalize`: Capitalize only the first letter\n- `titlecase`: Capitalize first letter of each word\n- `trim`: Remove leading and trailing whitespace",
    "parameters": [
      {
        "name": "transformation",
        "type": [
          {
            "value": "uppercase"
          },
          {
            "value": "lowercase"
          },
          {
            "value": "capitalize"
          },
          {
            "value": "titlecase"
          },
          {
            "value": "trim"
          }
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "textContent",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "formattedText",
        "type": [
          "ParameterType:string"
        ]
      }
    ],
    "category": "Text"
  },
  "getAttributesFromElement": {
    "systemName": "getAttributesFromElement",
    "description": "This operation retrieves the values for the specified attribute names from the given selected element.",
    "parameters": [
      {
        "name": "attributeNames",
        "type": [
          "ParameterType:array"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "attributeValues",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "DOM"
  },
  "getControllerFromElement": {
    "systemName": "getControllerFromElement",
    "description": "This operation retrieves the controller instance with the specified name that is assigned to the given selected element.",
    "parameters": [
      {
        "name": "controllerName",
        "type": [
          "ParameterType:controllerName"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "controllerInstance",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "Controller"
  },
  "getControllerInstance": {
    "systemName": "getControllerInstance",
    "description": "This operation retrieves an instance of the given controller name.\nIt assigns this instance to the `controllerInstance` property on the current operation data",
    "parameters": [
      {
        "name": "systemName",
        "type": [
          {
            "value": "DOMEventListenerController"
          },
          {
            "value": "LabelController"
          },
          {
            "value": "LottieController"
          },
          {
            "value": "NavigationController"
          },
          {
            "value": "ProgressbarController"
          },
          {
            "value": "RoutingController"
          },
          {
            "value": "SubtitlesController"
          }
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "controllerInstance",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "Controller"
  },
  "getCurrentTime": {
    "systemName": "getCurrentTime",
    "description": "Gets the current time as timestamp and Date object.",
    "parameters": [],
    "dependencies": [],
    "outputs": [
      {
        "name": "timestamp",
        "type": [
          "ParameterType:number"
        ]
      },
      {
        "name": "date",
        "type": [
          "ParameterType:Date"
        ]
      }
    ],
    "category": "Date"
  },
  "getElementDimensions": {
    "systemName": "getElementDimensions",
    "description": "This operation calculates the width and height of the given selected element.\nIt assigns this struct to the dimensions property on the current operation data.\nOptionally the width and height can be modified using the given modifier string.\n\nThe modifier string is formatted in the following way:\n\n<operator><amount><optional-side><optional-precentage>|<ratio-definition>\n\nWhere the ratio modifier is formatted in the following way:\n<side>[ar=<ratio-left>-<ratio-right>]\n\nFor example, this modifier '+100h|w[ar=8-1]' will modifiy the dimensions like this:\nit will add a value of 100 to the height and modify the width by a ratio of 8 to 1 relative to the height.",
    "parameters": [
      {
        "name": "modifier",
        "type": [
          "ParameterType:dimensionsModifier"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "dimensions",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "DOM"
  },
  "getFocusedElement": {
    "systemName": "getFocusedElement",
    "description": "Gets the currently focused element.",
    "parameters": [],
    "dependencies": [],
    "outputs": [
      {
        "name": "focusedElement",
        "type": [
          "ParameterType:jQuery"
        ]
      }
    ],
    "category": "Focus"
  },
  "getFormData": {
    "systemName": "getFormData",
    "description": "Extracts all input, select, and textarea values from form element into operation data.\n\nThis operation reads form field values and returns them as an object with field names as keys.\nOnly processes form elements that are enabled and not hidden. Handles checkboxes, radio buttons,\nselect elements, textareas, and text inputs.",
    "parameters": [],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "formData",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "Form"
  },
  "getImport": {
    "systemName": "getImport",
    "description": "This operation retrieves the import specified by the given `systemName` and\nassigns it to the `importedInstance` property on the current operaton date.",
    "parameters": [
      {
        "name": "systemName",
        "type": [
          "ParameterType:systemName"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "importedInstance",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "Utility"
  },
  "getQueryParams": {
    "systemName": "getQueryParams",
    "description": "This operation retrieves the current query parameters from the browser's address bar and places\nthem on the returned operation data.",
    "parameters": [
      {
        "name": "defaultValues",
        "type": [
          "ParameterType:object"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "queryParams",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "Utility"
  },
  "getScrollPosition": {
    "systemName": "getScrollPosition",
    "description": "Gets the current scroll position of the viewport.\n\nReturns x (horizontal) and y (vertical) scroll positions in pixels.\nUses cross-browser compatible methods to retrieve scroll position.",
    "parameters": [],
    "dependencies": [],
    "outputs": [
      {
        "name": "scrollX",
        "type": [
          "ParameterType:number"
        ]
      },
      {
        "name": "scrollY",
        "type": [
          "ParameterType:number"
        ]
      }
    ],
    "category": "Scroll"
  },
  "getTextContent": {
    "systemName": "getTextContent",
    "description": "Extracts text content from element, stripping all HTML markup.\n\nUses jQuery's `.text()` method which is XSS-safe and returns only the text content\nwithout any HTML tags. Preserves whitespace and text from nested elements.",
    "parameters": [],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "textContent",
        "type": [
          "ParameterType:string"
        ]
      }
    ],
    "category": "Text"
  },
  "httpDelete": {
    "systemName": "httpDelete",
    "description": "Performs an HTTP DELETE request to the specified URL.",
    "parameters": [
      {
        "name": "url",
        "type": [
          "ParameterType:string"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "headers",
        "type": [
          "ParameterType:object"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "response",
        "type": [
          "ParameterType:object"
        ]
      },
      {
        "name": "status",
        "type": [
          "ParameterType:number"
        ]
      }
    ],
    "category": "HTTP"
  },
  "httpPost": {
    "systemName": "httpPost",
    "description": "Performs an HTTP POST request to the specified URL.",
    "parameters": [
      {
        "name": "url",
        "type": [
          "ParameterType:string"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "body",
        "type": [
          "ParameterType:object"
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "headers",
        "type": [
          "ParameterType:object"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "response",
        "type": [
          "ParameterType:object"
        ]
      },
      {
        "name": "status",
        "type": [
          "ParameterType:number"
        ]
      }
    ],
    "category": "HTTP"
  },
  "httpPut": {
    "systemName": "httpPut",
    "description": "Performs an HTTP PUT request to the specified URL.",
    "parameters": [
      {
        "name": "url",
        "type": [
          "ParameterType:string"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "body",
        "type": [
          "ParameterType:object"
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "headers",
        "type": [
          "ParameterType:object"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "response",
        "type": [
          "ParameterType:object"
        ]
      },
      {
        "name": "status",
        "type": [
          "ParameterType:number"
        ]
      }
    ],
    "category": "HTTP"
  },
  "invokeObjectMethod": {
    "systemName": "invokeObjectMethod",
    "description": "This operation invokes the specified method on the given object with the given optional arguments\nand assigns the result to the `methodResult` operationdata property.",
    "parameters": [
      {
        "name": "methodName",
        "type": [
          "ParameterType:string"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "methodArguments",
        "type": [
          "ParameterType:array"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "instance",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "methodResult",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "Utility"
  },
  "isElementInViewport": {
    "systemName": "isElementInViewport",
    "description": "Checks if an element is currently visible within the viewport.\n\nUses `getBoundingClientRect()` to determine if the element is within the viewport boundaries.",
    "parameters": [],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "isInViewport",
        "type": [
          "ParameterType:boolean"
        ]
      }
    ],
    "category": "DOM"
  },
  "loadFromStorage": {
    "systemName": "loadFromStorage",
    "description": "Loads data from browser storage (localStorage or sessionStorage).\n\nDeserializes the stored JSON value. Returns `null` if key doesn't exist.",
    "parameters": [
      {
        "name": "key",
        "type": [
          "ParameterType:string"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "storageType",
        "type": [
          {
            "value": "local"
          },
          {
            "value": "session"
          }
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "loadedValue",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "Data"
  },
  "loadJson": {
    "systemName": "loadJson",
    "description": "This operation loads a JSON file from the specified url and assigns it to the json\nproperty on the current operation data.\n\nIf the cache property is set to true and a cached value already exists, this is assigned\ninstead of re-retrieving it from the url.",
    "parameters": [
      {
        "name": "url",
        "type": [
          "ParameterType:string"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "cache",
        "type": [
          "ParameterType:boolean"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "json",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "Utility"
  },
  "log": {
    "systemName": "log",
    "description": "This operation logs the specified value, or, when no logValue property has been assigned\nit will log the current operation data, global data and scope to the console",
    "parameters": [
      {
        "name": "logValue",
        "type": [
          "ParameterType:object",
          "ParameterType:string",
          "ParameterType:number",
          "ParameterType:boolean",
          "ParameterType:array"
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "logName",
        "type": [
          "ParameterType:string"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Utility"
  },
  "mapArray": {
    "systemName": "mapArray",
    "description": "Transforms each element of an array using a mapping function.\n\nOperates on arrayData passed from previous operations.\nThe mapFunction receives each item and optionally its index.",
    "parameters": [
      {
        "name": "mapFunction",
        "type": [
          "ParameterType:function"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "arrayData",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "mappedArray",
        "type": [
          "ParameterType:array"
        ]
      }
    ],
    "category": "Array"
  },
  "math": {
    "systemName": "math",
    "description": "This operation performs the given math function with the specified arguments.",
    "parameters": [
      {
        "name": "args",
        "type": [
          "ParameterType:array"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "functionName",
        "type": [
          "ParameterType:mathfunction"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "mathResult",
        "type": [
          "ParameterType:number"
        ]
      }
    ],
    "category": "Utility"
  },
  "otherwise": {
    "systemName": "otherwise",
    "description": "If the preceeding {@link when} operation evaluates to `true` subsequent operations will\nbe skipped until an {@link endWhen} operation is encountered.",
    "parameters": [],
    "dependencies": [],
    "outputs": [],
    "category": "Control Flow"
  },
  "removeClass": {
    "systemName": "removeClass",
    "description": "This operation removes the spcified class name from the given selected element.",
    "parameters": [
      {
        "name": "className",
        "type": [
          "ParameterType:className"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "DOM"
  },
  "removeControllerFromElement": {
    "systemName": "removeControllerFromElement",
    "description": "This operation removes the controller with the specified name from the given selected element.",
    "parameters": [
      {
        "name": "controllerName",
        "type": [
          "ParameterType:controllerName"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "Controller"
  },
  "removeElement": {
    "systemName": "removeElement",
    "description": "This operation removes the given selected element from the DOM.",
    "parameters": [],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "DOM"
  },
  "removePropertiesFromOperationData": {
    "systemName": "removePropertiesFromOperationData",
    "description": "This operation removes the given list of properties from the current operation data.\nIt will also remove the property `propertyNames` from the result.",
    "parameters": [
      {
        "name": "propertyNames",
        "type": [
          "ParameterType:array"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Data"
  },
  "reparentElement": {
    "systemName": "reparentElement",
    "description": "This operation moves the given selected element to the new parent that is defined\nby the specified `newParentSelector`.",
    "parameters": [
      {
        "name": "newParentSelector",
        "type": [
          "ParameterType:selector"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "DOM"
  },
  "replaceString": {
    "systemName": "replaceString",
    "description": "Replaces occurrences of a pattern in a string (alias for replaceText for string context).",
    "parameters": [
      {
        "name": "pattern",
        "type": [
          {
            "value": "string"
          },
          {
            "value": "RegExp"
          }
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "replacement",
        "type": [
          "ParameterType:string"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "textContent",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "result",
        "type": [
          "ParameterType:string"
        ]
      }
    ],
    "category": "String"
  },
  "replaceText": {
    "systemName": "replaceText",
    "description": "Finds and replaces text using literal string or regex pattern.\n\nOperates on textContent passed from previous operations (e.g., getTextContent).\nSupports regex patterns with global flag for multiple replacements.\nUpdates textContent with replaced text and sets replacementCount.",
    "parameters": [
      {
        "name": "searchPattern",
        "type": [
          {
            "value": "string"
          },
          {
            "value": "RegExp"
          }
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "replacement",
        "type": [
          "ParameterType:string"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "textContent",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "replacementCount",
        "type": [
          "ParameterType:number"
        ]
      }
    ],
    "category": "Text"
  },
  "requestAction": {
    "systemName": "requestAction",
    "description": "This operation requests an action instance with the specified name and assigns it\nto the `actionInstance` property on the current operation data.",
    "parameters": [
      {
        "name": "systemName",
        "type": [
          "ParameterType:actionName"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "actionInstance",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "Action"
  },
  "saveToStorage": {
    "systemName": "saveToStorage",
    "description": "Saves data to browser storage (localStorage or sessionStorage).\n\nSerializes the value as JSON before storing. Supports any JSON-serializable data type.",
    "parameters": [
      {
        "name": "key",
        "type": [
          "ParameterType:string"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "value",
        "type": [
          "ParameterType:object"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "storageType",
        "type": [
          {
            "value": "local"
          },
          {
            "value": "session"
          }
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Data"
  },
  "scrollToElement": {
    "systemName": "scrollToElement",
    "description": "Scrolls the viewport to bring the selected element into view.\n\nUses the browser's `scrollIntoView` API with configurable behavior.",
    "parameters": [
      {
        "name": "behavior",
        "type": [
          {
            "value": "auto"
          },
          {
            "value": "smooth"
          }
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "block",
        "type": [
          {
            "value": "start"
          },
          {
            "value": "center"
          },
          {
            "value": "end"
          },
          {
            "value": "nearest"
          }
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "inline",
        "type": [
          {
            "value": "start"
          },
          {
            "value": "center"
          },
          {
            "value": "end"
          },
          {
            "value": "nearest"
          }
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "Scroll"
  },
  "scrollToPosition": {
    "systemName": "scrollToPosition",
    "description": "Scrolls the viewport to a specific x,y coordinate position.\n\nUses the browser's `window.scrollTo` API with configurable behavior.",
    "parameters": [
      {
        "name": "x",
        "type": [
          "ParameterType:number"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "y",
        "type": [
          "ParameterType:number"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "behavior",
        "type": [
          {
            "value": "auto"
          },
          {
            "value": "smooth"
          }
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Scroll"
  },
  "selectElement": {
    "systemName": "selectElement",
    "description": "This operation selects one or more elements using the specified selector.\n\nIf `useSelectedElementAsRoot` is set to true and a valid DOM element is assigned\nto the current operation data's `selectedElement` property\nthen the element will be looked for only in the descendant elements of this DOM element.",
    "parameters": [
      {
        "name": "selector",
        "type": [
          "ParameterType:selector"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "useSelectedElementAsRoot",
        "type": [
          "ParameterType:boolean"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [
      {
        "name": "selectedElement",
        "type": [
          "ParameterType:object"
        ]
      }
    ],
    "category": "DOM"
  },
  "setData": {
    "systemName": "setData",
    "description": "This operation assigns the specified properties to the specified data targets.",
    "parameters": [
      {
        "name": "properties",
        "type": [
          "ParameterType:object"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Data"
  },
  "setElementAttributes": {
    "systemName": "setElementAttributes",
    "description": "This operation sets the specified set of attributes on the given selected element.",
    "parameters": [
      {
        "name": "attributes",
        "type": [
          "ParameterType:object"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "DOM"
  },
  "setElementContent": {
    "systemName": "setElementContent",
    "description": "This operation sets the specified content defined by the value assigned to the template property\nto the given selected element.\n\nWhen the `insertionType` is set to `overwrite` the contents of the selected element are replaced\nby the given template.\nWhen set to `append` the new content will be inserted after the current content.\nWhen set to `prepend` the new content will be inserted before the current content.",
    "parameters": [
      {
        "name": "template",
        "type": [
          {
            "value": "string"
          },
          {
            "value": "Element"
          },
          {
            "value": "Text"
          },
          {
            "value": "Comment"
          },
          {
            "value": "Document"
          },
          {
            "value": "DocumentFragment"
          }
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "insertionType",
        "type": [
          {
            "value": "overwrite"
          },
          {
            "value": "append"
          },
          {
            "value": "prepend"
          }
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "DOM"
  },
  "setFocus": {
    "systemName": "setFocus",
    "description": "Sets focus to the selected element.",
    "parameters": [],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "Focus"
  },
  "setFormValue": {
    "systemName": "setFormValue",
    "description": "Sets the value of an input, select, or textarea element.\n\nHandles different input types appropriately:\n- Text inputs, textareas, selects: sets value directly\n- Checkboxes: sets checked property for boolean values\n- Radio buttons: sets checked property for boolean values\n- Number inputs: converts to string",
    "parameters": [
      {
        "name": "value",
        "type": [
          {
            "value": "string"
          },
          {
            "value": "number"
          },
          {
            "value": "false"
          },
          {
            "value": "true"
          }
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "Form"
  },
  "setGlobalData": {
    "systemName": "setGlobalData",
    "description": "This operation copies the specified properties from the operationData to the global data.",
    "parameters": [
      {
        "name": "propertyNames",
        "type": [
          "ParameterType:array"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Data"
  },
  "setOperationData": {
    "systemName": "setOperationData",
    "description": "This operation assigns the specified properties to the current operation data.\nWhen override is set to true the properties replace the current operation data entirely.",
    "parameters": [
      {
        "name": "properties",
        "type": [
          "ParameterType:object"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "override",
        "type": [
          "ParameterType:boolean"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Data"
  },
  "setStyle": {
    "systemName": "setStyle",
    "description": "This operation assigns the specified CSS style properties to the\ngiven selected element.",
    "parameters": [
      {
        "name": "properties",
        "type": [
          "ParameterType:cssProperties"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "DOM"
  },
  "setVariable": {
    "systemName": "setVariable",
    "description": "This operation sets a variable with the specified name on the scope with the specified value.",
    "parameters": [
      {
        "name": "name",
        "type": [
          "ParameterType:string"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "value",
        "type": [
          "ParameterType:object",
          "ParameterType:string",
          "ParameterType:number",
          "ParameterType:boolean",
          "ParameterType:array"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Data"
  },
  "sortArray": {
    "systemName": "sortArray",
    "description": "Sorts an array by property, natural order, or custom comparator function.\n\nOperates on arrayData passed from previous operations.\nSupports three sorting modes:\n1. Property sort: `sortProperty` and `sortOrder` to sort objects by property\n2. Natural sort: `sortOrder` alone for primitive arrays\n3. Custom comparator: `sortComparator` function for complex sorting logic",
    "parameters": [
      {
        "name": "sortProperty",
        "type": [
          "ParameterType:string"
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "sortOrder",
        "type": [
          {
            "value": "asc"
          },
          {
            "value": "desc"
          }
        ],
        "required": false,
        "erased": true
      },
      {
        "name": "sortComparator",
        "type": [
          "ParameterType:function"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "arrayData",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "sortedArray",
        "type": [
          "ParameterType:array"
        ]
      }
    ],
    "category": "Array"
  },
  "splitString": {
    "systemName": "splitString",
    "description": "Splits a string into an array by delimiter (string or regex).",
    "parameters": [
      {
        "name": "delimiter",
        "type": [
          {
            "value": "string"
          },
          {
            "value": "RegExp"
          }
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "limit",
        "type": [
          "ParameterType:number"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "textContent",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "resultArray",
        "type": [
          "ParameterType:array"
        ]
      }
    ],
    "category": "String"
  },
  "startAction": {
    "systemName": "startAction",
    "description": "This operation starts the specified action instance using the given action operation data.\n\nThe action operation data is first merged with the current operation data before it is\npassed on to the action. After the action has completed the action operation data properties\nare removed from the current operation data.",
    "parameters": [
      {
        "name": "actionOperationData",
        "type": [
          "ParameterType:object"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "actionInstance",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "Action"
  },
  "substringText": {
    "systemName": "substringText",
    "description": "Extracts a substring from text between start and end indices.",
    "parameters": [
      {
        "name": "start",
        "type": [
          "ParameterType:number"
        ],
        "required": true,
        "erased": true
      },
      {
        "name": "end",
        "type": [
          "ParameterType:number"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "textContent",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "substring",
        "type": [
          "ParameterType:string"
        ]
      }
    ],
    "category": "Text"
  },
  "toggleClass": {
    "systemName": "toggleClass",
    "description": "This operation toggles the specfied class name on the given selected element.\n\nMeaning, if the specified class name exists on the given element it will be removed,\notherwise it will be added.",
    "parameters": [
      {
        "name": "className",
        "type": [
          "ParameterType:className"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "DOM"
  },
  "toggleElement": {
    "systemName": "toggleElement",
    "description": "This operation toggles the visibility of the given selected element.\n\nMeaning, if the element is hidden, it will be made visible, otherwise\nit will be hidden.",
    "parameters": [],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "DOM"
  },
  "toggleFormElement": {
    "systemName": "toggleFormElement",
    "description": "Enables or disables form input elements (inputs, selects, textareas, buttons).\n\nSets the `disabled` property on the element. When `enabled` is true, removes the disabled\nattribute; when false, adds the disabled attribute.",
    "parameters": [
      {
        "name": "enabled",
        "type": [
          "ParameterType:boolean"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [],
    "category": "Form"
  },
  "validateForm": {
    "systemName": "validateForm",
    "description": "Validates form fields against HTML5 validation and custom rules.\n\nUses HTML5 validation API (checkValidity()) for native validation, and supports\ncustom validation rules for: required, minLength, maxLength, pattern (regex), and email format.",
    "parameters": [
      {
        "name": "validationRules",
        "type": [
          "ParameterType:object"
        ],
        "required": false,
        "erased": true
      }
    ],
    "dependencies": [
      {
        "name": "selectedElement",
        "type": "ParameterType:object"
      }
    ],
    "outputs": [
      {
        "name": "validationErrors",
        "type": [
          "ParameterType:object"
        ]
      },
      {
        "name": "isValid",
        "type": [
          "ParameterType:boolean"
        ]
      }
    ],
    "category": "Form"
  },
  "wait": {
    "systemName": "wait",
    "description": "This operation waits for the specified amount of milliseconds.",
    "parameters": [
      {
        "name": "milliseconds",
        "type": [
          "ParameterType:number"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Utility"
  },
  "when": {
    "systemName": "when",
    "description": "When the given expression evaluates to false, subsequent operations will be skipped\nuntil an {@link endWhen} or {@link otherwise} operation is encountered.\n\nPractically, this means an `if` or `if`/`else` statement control flow implementation in a list of operations.\n\nThe expression is passed in as a formatted string.\nThe left and right values of the expression can be defined like this:\n\n'constant': for a constant string\n100: for a constant number\n$operationData.foo: for an operation data value\n$globaldata.foo: for a global data value\n$scope.loopIndex: for a scope value",
    "parameters": [
      {
        "name": "expression",
        "type": [
          "ParameterType:expression"
        ],
        "required": true,
        "erased": true
      }
    ],
    "dependencies": [],
    "outputs": [],
    "category": "Control Flow"
  }
};
