/**
 * AST Helper Utilities
 *
 * Provides type guards and helper functions for working with Eligian AST nodes.
 *
 * Note: This module re-exports Langium-generated type guards for convenience.
 * The actual type guard implementations are generated by Langium in `generated/ast.ts`.
 *
 * @module ast-helpers
 */

import type { AstNode } from 'langium';
import type {
  ActionDefinition,
  DefaultImport,
  EventActionDefinition,
  ImportStatement,
  LibraryImport,
  NamedImport,
  ProgramElement,
} from '../generated/ast.js';
import {
  isActionDefinition as generatedIsActionDefinition,
  isDefaultImport as generatedIsDefaultImport,
  isEventActionDefinition as generatedIsEventActionDefinition,
  isImportStatement as generatedIsImportStatement,
  isLibraryImport as generatedIsLibraryImport,
  isNamedImport as generatedIsNamedImport,
  isProgramElement as generatedIsProgramElement,
} from '../generated/ast.js';

/**
 * Type guard for DefaultImport AST nodes
 *
 * Delegates to Langium-generated type guard.
 *
 * @param node - AST node to check
 * @returns true if node is a DefaultImport, false otherwise
 *
 * @example
 * ```typescript
 * if (isDefaultImport(node)) {
 * }
 * ```
 */
export function isDefaultImport(node: AstNode | undefined): node is DefaultImport {
  return generatedIsDefaultImport(node);
}

/**
 * Type guard for NamedImport AST nodes
 *
 * Delegates to Langium-generated type guard.
 *
 * @param node - AST node to check
 * @returns true if node is a NamedImport, false otherwise
 *
 * @example
 * ```typescript
 * if (isNamedImport(node)) {
 * }
 * ```
 */
export function isNamedImport(node: AstNode | undefined): node is NamedImport {
  return generatedIsNamedImport(node);
}

/**
 * Type guard for ImportStatement AST nodes
 *
 * Delegates to Langium-generated type guard.
 *
 * @param node - AST node to check
 * @returns true if node is an ImportStatement (DefaultImport or NamedImport), false otherwise
 *
 * @example
 * ```typescript
 * if (isImportStatement(node)) {
 *   // node is either DefaultImport or NamedImport
 * }
 * ```
 */
export function isImportStatement(node: AstNode | undefined): node is ImportStatement {
  return generatedIsImportStatement(node);
}

/**
 * Type guard for ProgramElement AST nodes
 *
 * Delegates to Langium-generated type guard.
 *
 * @param node - AST node to check
 * @returns true if node is a ProgramElement (ActionDefinition, Timeline, or VariableDeclaration), false otherwise
 *
 * @example
 * ```typescript
 * if (isProgramElement(node)) {
 *   // node is ActionDefinition, Timeline, or VariableDeclaration
 * }
 * ```
 */
export function isProgramElement(node: AstNode | undefined): node is ProgramElement {
  return generatedIsProgramElement(node);
}

/**
 * Type guard for ActionDefinition AST nodes
 *
 * Delegates to Langium-generated type guard.
 *
 * @param node - AST node to check
 * @returns true if node is an ActionDefinition (RegularActionDefinition or EndableActionDefinition), false otherwise
 *
 * @example
 * ```typescript
 * if (isActionDefinition(node)) {
 * }
 * ```
 */
export function isActionDefinition(node: AstNode | undefined): node is ActionDefinition {
  return generatedIsActionDefinition(node);
}

/**
 * Type guard for LibraryImport AST nodes
 *
 * Delegates to Langium-generated type guard.
 *
 * @param node - AST node to check
 * @returns true if node is a LibraryImport, false otherwise
 *
 * @example
 * ```typescript
 * if (isLibraryImport(node)) {
 *   // node is a library import statement
 * }
 * ```
 */
export function isLibraryImport(node: AstNode | undefined): node is LibraryImport {
  return generatedIsLibraryImport(node);
}
/**
 * Type guard for EventActionDefinition AST nodes
 *
 * Delegates to Langium-generated type guard.
 *
 * @param node - AST node to check
 * @returns true if node is an EventActionDefinition, false otherwise
 *
 * @example
 * ```typescript
 * if (isEventActionDefinition(node)) {
 *   // node is an event-triggered action
 * }
 * ```
 */
export function isEventActionDefinition(node: AstNode | undefined): node is EventActionDefinition {
  return generatedIsEventActionDefinition(node);
}
